#每天 16:00 执行
name: crds

on:
   gollum:
   schedule:
       - cron: '0 9 * * *'
jobs:
  start:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: run
      run: |
        pip install -r requirement.txt
        python mrds.py
