#每天 16:00 执行
name: crds

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 8 * * *'
jobs:
  start:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: run
      env:
        AGENTID: ${{ secrets.AGENTID }}
        COOLPUSHURL: ${{ secrets.COOLPUSHURL }}
        CORPID: ${{ secrets.CORPID }}
        CORPSECRET: ${{ secrets.CORPSECRET }}
        IMG_URL: ${{ secrets.IMG_URL }}
        PUSHUSR: ${{ secrets.PUSHUSR }}
      run: |
        pip install -r requirement.txt
        python mrds.py
